[package]
name = "ratatui_frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29"
thiserror = { workspace = true }
tokio = { workspace = true }

chat_backend = { workspace = true }
