[package]
name = "chat_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { workspace = true }
protocol = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

[lints]
workspace = true
