[package]
name = "chat_server"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

network_protocol = { workspace = true }

[lints]
workspace = true
