[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = { workspace = true }
prost-types = "0.14"
tokio-util = { workspace = true }

[build-dependencies]
prost-build = "0.14"

[lints]
workspace = true
